steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'backend/Dockerfile', '-t', 'asia-northeast3-docker.pkg.dev/bridge-487513/cloud-run-source-deploy/wakain-api', '.']
images: ['asia-northeast3-docker.pkg.dev/bridge-487513/cloud-run-source-deploy/wakain-api']
